default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  poot: 3306
  password: password # デフォルトだと空欄になっているので変更
  host: db # デフォルトだとlocalhostになっているので変更

development:
  <<: *default
  database: yosa_management_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: yosa_management_production
  username: root
  password: <%= ENV["DATABASE_PASSWORD"] %>
  socket: /var/lib/mysql/mysql.sock