default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  poot: 3306
  host: db

development:
  <<: *default
  database: yosa_management_development
  password: password
  host: db

test:
  <<: *default
  database: myapp_test
  password: password
  host: db

production:
  <<: *default
  database: yosa_management_production
  username: root
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["HOST_NAME"] %>